version: 2

updates:
  # Surveillance des GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    reviewers:
      - "ryannnasa"
    assignees:
      - "ryannnasa"
    commit-message:
      prefix: "🔧"
    labels:
      - "github-actions"
      - "ci/cd"

  # Surveillance Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
    reviewers:
      - "ryannnasa"
    assignees:
      - "ryannnasa"
    commit-message:
      prefix: "🐳"
    labels:
      - "docker"
