name: Pipeline Frontend Docker Image

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Define git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump patch version
        run: |
          npm version ${{ github.ref_name }}

      - name: Commit and push version bump
        run: |
          git commit -m "ci: bump version [skip ci]" || echo "No changes to commit"
          git push origin HEAD:master || echo "No changes to push"

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: maximerobin44/old-world-realms-front:${{ github.ref_name }}

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: maximerobin44/old-world-realms-front:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig

      - name: Inject environment variables into deployment.yaml
        run: |
          envsubst < k8s/deployment.yaml > k8s/deployment.generated.yaml
        env:
          VERSION: ${{ github.ref_name }}

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          kubectl apply -f k8s/deployment.generated.yaml
