name: Build & Push Frontend Docker Image

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Debug version
        run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.ref: ${{ github.ref }}"
          echo "GITHUB_REF: $GITHUB_REF"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump patch version
        run: |
          npm version ${{ github.ref_name }}

      - name: Commit and push version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json || true
          git commit -m "ci: bump version [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: maximerobin44/old-world-realms-front:${{ github.ref_name }}

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: maximerobin44/old-world-realms-front:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig

      - name: Inject environment variables into deployment.yaml
        run: |
          envsubst < k8s/deployment.yaml > k8s/deployment.generated.yaml
        env:
          VERSION: ${{ github.ref_name }}

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          kubectl apply -f k8s/deployment.generated.yaml
